apiVersion: v2
appVersion: 1.12.1
dependencies:
- condition: zookeeper.enabled
  name: zookeeper
  repository: https://charts.bitnami.com/bitnami
  version: 5.23.0
- alias: registry
  condition: registry.enabled
  name: nifi-registry
  repository: https://dysnix.github.io/charts/
  version: 0.1.1
- condition: ca.enabled
  name: ca
  repository: ""
  version: 1.0.1
description: Apache NiFi is a software project from the Apache Software Foundation
  designed to automate the flow of data between software systems.
home: https://nifi.apache.org/
icon: https://svn.apache.org/repos/asf/nifi/site/trunk/images/niFi-logo-horizontal-scaled.png
keywords:
- nifi
- data
- process
maintainers:
- email: alexandre.nuttinck@cetic.be
  name: alexnuttinck
  url: https://github.com/alexnuttinck
name: nifi
version: 0.6.2
